plugins:
  upvotes_enabled:
    client: true
    default: true
  upvotes_undo_vote_action_window:
    default: 10
  upvotes_comment_limit_per_post:
    default: 10
    min: 1
    client: true
  upvotes_comment_max_raw_length:
    client: true
    hidden: true
    default: 600
  upvotes_enable_likes_on_answers:
    client: true
    default: false
